---
# iptables-Regeln für NAT-Masquerading und Rate-Limiting

- name: iptables-persistent installieren (Debian/Ubuntu)
  apt:
    name:
      - iptables-persistent
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: netfilter-persistent installieren (RedHat/CentOS)
  yum:
    name:
      - iptables-services
    state: present
  when: ansible_os_family == "RedHat"

- name: Verzeichnis für iptables-Regeln erstellen
  file:
    path: "/etc/iptables"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: iptables-Regeln aus Template erstellen
  template:
    src: "iptables-rules.v4.j2"
    dest: "/etc/iptables/rules.v4"
    mode: '0644'
    owner: root
    group: root
  notify: apply iptables rules

- name: netfilter-persistent Service aktivieren (Debian)
  systemd:
    name: netfilter-persistent
    enabled: yes
    state: started
  when: ansible_os_family == "Debian"

- name: iptables Service aktivieren (RedHat/CentOS)
  systemd:
    name: iptables
    enabled: yes
  when: ansible_os_family == "RedHat"

